######################################################################
# Automatically generated by qmake (3.1) Fri May 6 16:55:28 2022
######################################################################

TEMPLATE = app
TARGET = diagram_editor
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += src/gui/window.h \
           src/core/open-file/open_file.h \
           src/core/save-file/save_file.h \
           src/core/verification/verification.h \
           src/gui/canvas/canvas.h \
           src/gui/menu/menu.h \
           src/gui/side-toolbox/side_toolbox.h \
           src/gui/canvas/class-diagram/class_diagram.h \
           src/gui/canvas/sequence-diagram/sequence_diagram.h \
           src/gui/side-toolbox/input-entity/input_entity.h \
           src/gui/side-toolbox/resizer/resizer.h \
           src/gui/canvas/class-diagram/entity/entity.h \
           src/gui/canvas/class-diagram/relation/relation_line.h \
           src/gui/canvas/class-diagram/text-item/text_item.h \
           src/gui/canvas/class-diagram/undo-redo/undo_redo.h \
           src/gui/canvas/sequence-diagram/actor/actor.h \
           src/gui/canvas/sequence-diagram/box/box.h \
           src/gui/canvas/sequence-diagram/lifeline/lifeline.h \
           src/gui/canvas/sequence-diagram/message/message.h \
           src/gui/canvas/sequence-diagram/object/object.h \
           src/gui/canvas/class-diagram/entity/class_info/class_info.h \
           src/gui/canvas/class-diagram/entity/entity-text/entity_text.h \
           src/gui/canvas/class-diagram/relation/relation-point/relation_point.h \
           src/gui/canvas/class-diagram/relation/relation-text/relation_text.h \
           src/gui/canvas/sequence-diagram/message/point/point.h
SOURCES += src/main.cpp \
           src/gui/window.cpp \
           src/core/open-file/open_file.cpp \
           src/core/save-file/save_file.cpp \
           src/core/verification/verification.cpp \
           src/gui/canvas/canvas.cpp \
           src/gui/menu/menu.cpp \
           src/gui/side-toolbox/side_toolbox.cpp \
           src/gui/canvas/class-diagram/class_diagram.cpp \
           src/gui/canvas/sequence-diagram/sequence_diagram.cpp \
           src/gui/side-toolbox/input-entity/input_entity.cpp \
           src/gui/side-toolbox/resizer/resizer.cpp \
           src/gui/canvas/class-diagram/entity/entity.cpp \
           src/gui/canvas/class-diagram/relation/relation_line.cpp \
           src/gui/canvas/class-diagram/text-item/text_item.cpp \
           src/gui/canvas/class-diagram/undo-redo/undo_redo.cpp \
           src/gui/canvas/sequence-diagram/actor/actor.cpp \
           src/gui/canvas/sequence-diagram/box/box.cpp \
           src/gui/canvas/sequence-diagram/lifeline/lifeline.cpp \
           src/gui/canvas/sequence-diagram/message/message.cpp \
           src/gui/canvas/sequence-diagram/object/object.cpp \
           src/gui/canvas/class-diagram/entity/class_info/class_info.cpp \
           src/gui/canvas/class-diagram/entity/entity-text/entity_text.cpp \
           src/gui/canvas/class-diagram/relation/relation-point/relation_point.cpp \
           src/gui/canvas/class-diagram/relation/relation-text/relation_text.cpp \
           src/gui/canvas/sequence-diagram/message/point/point.cpp

QT+=core widgets
